# Step 15: a small CMake script, run at build time via `cmake -P` from add_custom_command.
# CMAKE_ARGV3 is the first argument after the script path (argv0=cmake, argv1=-P, argv2=script).
file(WRITE ${CMAKE_ARGV3} "#pragma once\n#define BUILD_INFO \"generated by CMake\"\n")
